
DROP TABLE BBS 
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BBS;


CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	
	REF NUMBER(8) NOT NULL,
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
	
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL
	
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

-- 외래키 설정하기 (ID)
ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY (ID)
REFERENCES MEMBER(ID);


select * from bbs

INSERT INTO BBS
VALUES ( SEQ_BBS.NEXTVAL, 'asd', 0, 0, 0, 'asd1', 'asd1', '2020-1-30', 0, 0  )

INSERT INTO BBS ( SEQ, ID,REF, STEP, DEPTH, TITLE, CONTENT, WDATE, DEL, READCOUNT ) 
 VALUES ( SEQ_BBS.NEXTVAL, 'asd',  (SELECT NVL(MAX(REF), 0)+1 FROM BBS), 0, 0, 'title', 'content', SYSDATE,  0, 0 );
