-- 기존 테이블 데이터 지우기
DROP TABLE MEMBER
CASCADE CONSTRAINTS;


-- 생성하기
CREATE TABLE MEMBER(
	ID VARCHAR2(50) PRIMARY KEY,
	PWD VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE,
	AUTH NUMBER(1) NOT NULL
);

select * from Member;

 INSERT INTO MEMBER ( ID, PWD, NAME, EMAIL, AUTH )
 VALUES ( 'AA', 'BB', 'CC', 'DD', 3 )